In [56]:
#Creating Database 
import mysql.connector as connection
class DB:
    def __init__(self):
        self.con = connection.connect(host = "localhost",
                                     username = "root",
                                     password = "Arzoo@6552",
                                     database = " mysqlday1"
                                     
                                    )
        cur = self.con.cursor()
        print("Connected\n",self.con)
        query = "create table if not exists Student(name varchar(25) , rollid int Primary key , section varchar(25))"
        cur.execute(query)
        
    def insert_student(self,name,rollid,section):
        query = "insert into Student(name,rollid,section)values('{}',{},'{}')".format(name,rollid,section)
        print(query)
        cur  =  self.con.cursor()
        cur.execute(query)
        self.con.commit()
        print("user saved to db")
    
    def fetch_all(self):
        query = "select * from student"
        cur = self.con.cursor()
        cur.execute(query)
        for row in cur:
            print("name:",row[0])
            print("rollid:",row[1])
            print("section:",row[2])
            print("\n")
    def fetch_data(self,rollid):
        query = "select * from student where rollid ={}".format(rollid)
        cur = self.con.cursor()
        cur.execute(query)
        for row in cur:
            print("name:",row[0])
            print("rollid:",row[1])
            print("section:",row[2])
            print("\n")
    #delete the stu
    def delete_data(self,rollid):
        query = "delete from student where rollid= {}".format(rollid)
        print(query)
        cur = self.con.cursor()
        cur.execute(query)
        self.con.commit()
        print("deleted")
    def update_data(self,rollid,username):
        query = "update student set name = '{}' where rollid = {}".format(username,rollid)
        print(query)
        cur = self.con.cursor()
        cur.execute(query)
        self.con.commit()
        print("updated")
        
db = DB()
# db.insert_student("Arun",5,"cs1")
# db.insert_student("Barun",2,"cs2")
# db.insert_student("Crun",3,"cs3")
# db.insert_student("Drun",4,"cs4")
# db.fetch_all()
# db.fetch_data(2)
# db.delete_data(3)
# db.fetch_all()
# db.update_data(1,"Pankaj")
db.fetch_all()

Connected
 <mysql.connector.connection_cext.CMySQLConnection object at 0x00000206D4934D00>
name: Arun
rollid: 1
section: cs1


name: Drun
rollid: 4
section: cs4

In [ ]:
import mysql.connector as connection
class DB_Helper:
    def __init__(self):
        self.con = connection.connect(host="localhost",
                                     username = "root",
                                     password = "Arzoo@6552",
                                     database = 'org1'
                                     )
        query = '''create table if not exists worker(worker_id int primary key,
                                    first_name varchar(25) ,
                                    last_name varchar(25),
                                    salary int(10) , 
                                    joining_date datetime, 
                                    department varchar(25))'''
        
      
        cur = self.con.cursor()
        cur.execute(query)
        print("Connected....")
    
    def insert_data(self,worker_id,first_name,last_name,salary,joining_date,department):
        query = '''insert into worker(worker_id,first_name,last_name,salary,joining_date,department) values({} ,'{}', 
                                    '{}',{} ,'{}', '{}')'''.format(worker_id,first_name,last_name,salary,joining_date,department)
        
        print(query)
        cur  =  self.con.cursor()
        cur.execute(query)
        self.con.commit()
        print("user saved to db")
        
        
            
            
db = DB_Helper()
db.insert_data("%03d" % (1,), 'Monika', 'Arora', 100000, '14-02-20 09.00.00', 'HR')
db.insert_data("%03d" % (2,),'Niharika', 'Verma', 80000, '2014-06-11 09.00.00', 'Admin')
db.insert_data("%03d" % (3,), 'Vishal', 'Singhal', 300000, '14-02-20 09.00.00', 'HR')
db.insert_data("%03d" % (4,), 'Amitabh', 'Singh', 500000, '14-02-20 09.00.00', 'Admin')
db.insert_data("%03d" % (5,), 'Vivek', 'Bhati', 500000, '14-06-11 09.00.00', 'Admin')
db.insert_data("%03d" % (6,), 'Vipul', 'Diwan', 200000, '14-06-11 09.00.00', 'Account')
db.insert_data("%03d" % (7,), 'Satish', 'Kumar', 75000, '14-01-20 09.00.00', 'Account')
db.insert_data("%03d" % (8,), 'Geetika', 'Chauhan', 90000, '14-04-11 09.00.00', 'Admin')